name: Docker Image CI

on:
  push:
    paths-ignore: 
      - "README.md"
    branches:
    - master
  schedule:
    - cron:  "0 0 * * 0"
  pull_request:
    paths-ignore: 
      - "README.md"
    branches:
    - master
      

jobs:
  
  build:
    name: Omada Controller ${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:        
        include:
          - version: 3.2.10
            repo: "https://static.tp-link.com/2020/202004/20200420"
            tag: 3.2.10-lts-20,3.2.10,latest
            os: ubuntu:20.04
            locales: 2.31-0ubuntu9
            tzdata: 2019c-3ubuntu1
            tar: 1.30+dfsg-7
            wget: 1.20.3-1ubuntu1
          - version: 3.2.10
            repo: "https://static.tp-link.com/2020/202004/20200420"
            tag: 3.2.10-lts-18 
            os: ubuntu:18.04
            locales: 2.27-3ubuntu1
            tzdata: 2020a-0ubuntu0.18.04
            tar: 1.29b-2ubuntu0.1
            wget: 1.19.4-1ubuntu2.2
          
          - version: 3.2.9
            repo: "https://static.tp-link.com/2020/202004/20200409"
            tag: 3.2.9-lts-20,3.2.9
            os: ubuntu:20.04
            locales: 2.31-0ubuntu9
            tzdata: 2019c-3ubuntu1
            tar: 1.30+dfsg-7
            wget: 1.20.3-1ubuntu1      
          - version: 3.2.9
            repo: "https://static.tp-link.com/2020/202004/20200409"
            tag: 3.2.9-lts-18 
            os: ubuntu:18.04
            locales: 2.27-3ubuntu1
            tzdata: 2020a-0ubuntu0.18.04
            tar: 1.29b-2ubuntu0.1
            wget: 1.19.4-1ubuntu2.2
            
          - version: 3.2.6
            repo: "https://static.tp-link.com/2020/202001/20200116"
            tag: 3.2.6-lts-20,3.2.6
            os: ubuntu:20.04           
            locales: 2.31-0ubuntu9
            tzdata: 2019c-3ubuntu1
            tar: 1.30+dfsg-7
            wget: 1.20.3-1ubuntu1
          - version: 3.2.6
            repo: "https://static.tp-link.com/2020/202001/20200116"
            tag: 3.2.6-lts-18 
            os: ubuntu:18.04
            locales: 2.27-3ubuntu1
            tzdata: 2020a-0ubuntu0.18.04
            tar: 1.29b-2ubuntu0.1
            wget: 1.19.4-1ubuntu2.2
            
          - version: 3.2.4
            repo: "https://static.tp-link.com/2019/201911/20191108"
            tag: 3.2.4-lts-20,3.2.4
            os: ubuntu:20.04           
            locales: 2.31-0ubuntu9
            tzdata: 2019c-3ubuntu1
            tar: 1.30+dfsg-7
            wget: 1.20.3-1ubuntu1
          - version: 3.2.4
            repo: "https://static.tp-link.com/2019/201911/20191108"
            tag: 3.2.4-lts-18 
            os: ubuntu:18.04
            locales: 2.27-3ubuntu1
            tzdata: 2020a-0ubuntu0.18.04
            tar: 1.29b-2ubuntu0.1
            wget: 1.19.4-1ubuntu2.2
          
          - version: 3.2.1
            repo: "https://static.tp-link.com/2019/201909/20190906"
            tag: 3.2.1-lts-20,3.2.1
            os: ubuntu:20.04           
            locales: 2.31-0ubuntu9
            tzdata: 2019c-3ubuntu1
            tar: 1.30+dfsg-7
            wget: 1.20.3-1ubuntu1
          - version: 3.2.1
            repo: "https://static.tp-link.com/2019/201909/20190906"
            tag: 3.2.1-lts-18 
            os: ubuntu:18.04
            locales: 2.27-3ubuntu1
            tzdata: 2020a-0ubuntu0.18.04
            tar: 1.29b-2ubuntu0.1
            wget: 1.19.4-1ubuntu2.2
    steps:
      - uses: actions/checkout@v1
      
      - uses: docker/build-push-action@v1
        env:
          DOCKER_BUILDKIT: "1"
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          add_git_labels: true
          repository: thost96/omada
          tags: ${{ matrix.tag }}
          build_args: BASEIMAGE=${{matrix.os}},OMADA_VERSION=${{matrix.version}},OMADA_REPO=${{matrix.repo}},LOCALES_VERSION=${{matrix.locales}},TZDATA_VERSION=${{matrix.tzdata}},TAR_VERSION=${{matrix.tar}},WGET_VERSION=${{matrix.wget}}

  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest         
    steps:
      - uses: actions/checkout@v1
      - uses: brpaz/hadolint-action@master
  
  securitycheck:
     name: Trivy - Scan for Vuls 
     runs-on: ubuntu-latest
     strategy:
      fail-fast: false
      matrix:
        tags: [latest, 3.2.10-lts-20, 3.2.10-lts-18, 3.2.9-lts-20, 3.2.9-lts-18, 3.2.6-lts-20, 3.2.6-lts-18, 3.2.4-lts-20, 3.2.4-lts-18, 3.2.1-lts-20, 3.2.1-lts-18]
     steps:
        - name: Login to DockerHub Registry
          run: echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
        - name: Pull docker image
          run: docker pull ${{secrets.DOCKER_USER }}/omada:${{ matrix.tags }}
        - name: Trivy Action
          uses: homoluctus/gitrivy@v2  
          with:
            image: ${{secrets.DOCKER_USER }}/omada:${{ matrix.tags }}
            token: ${{ secrets.GITHUB_TOKEN }}
  
  security:
    name: Snyk - Security Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:        
        tag: [latest, 3.2.10-lts-20, 3.2.10-lts-18, 3.2.9-lts-20, 3.2.9-lts-18, 3.2.6-lts-20, 3.2.6-lts-18, 3.2.4-lts-20, 3.2.4-lts-18, 3.2.1-lts-20, 3.2.1-lts-18]
    steps:
        - uses: actions/checkout@master
        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/docker@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
            image: ${{secrets.DOCKER_USER }}/omada:${{matrix.tag}}
            args: --severity-threshold=high
