name: Docker Image CI for Alpine based Image

on:
  push:
    paths-ignore: 
      - "README.md"
    branches:
    - alpine
  schedule:
    - cron:  "0 0 * * 0"
  pull_request:
    paths-ignore: 
      - "README.md"
    branches:
    - alpine
      

jobs:
  
  build:
    name: Omada Controller ${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        os: alpine:3.11.6           
        glibc: 2.29-r0
        tzdata: 2020a-r0
        tar: 1.32-r1
        wget: 1.20.3-r0
        include:
          - version: 3.2.10
            repo: "https://static.tp-link.com/2020/202004/20200420"
            tag: 3.2.10-alpine,alpine
          
          - version: 3.2.9
            repo: "https://static.tp-link.com/2020/202004/20200409"
            tag: 3.2.9-alpine    
            
          - version: 3.2.6
            repo: "https://static.tp-link.com/2020/202001/20200116"
            tag: 3.2.6-alpine
            
          - version: 3.2.4
            repo: "https://static.tp-link.com/2019/201911/20191108"
            tag: 3.2.4-alpine
          
          - version: 3.2.1
            repo: "https://static.tp-link.com/2019/201909/20190906"
            tag: 3.2.1-alpine

    steps:
      - uses: actions/checkout@v1
      
      - uses: docker/build-push-action@v1
        env:
          DOCKER_BUILDKIT: "1"
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          add_git_labels: true
          repository: thost96/omada
          tags: ${{ matrix.tag }}
          build_args: BASEIMAGE=${{matrix.os}},OMADA_VERSION=${{matrix.version}},OMADA_REPO=${{matrix.repo}},LOCALES_VERSION=${{matrix.locales}},TZDATA_VERSION=${{matrix.tzdata}},TAR_VERSION=${{matrix.tar}},WGET_VERSION=${{matrix.wget}}

  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest         
    steps:
      - uses: actions/checkout@v1
      - uses: brpaz/hadolint-action@master
