---
name: Docker Image CI

on:
  push:
    paths-ignore: 
      - "README.md"
  pull_request:
    paths-ignore: 
      - "README.md"

jobs:
  build:
    name: Omada Controller ${{ matrix.tag }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 3.2.16
            repo: "https://static.tp-link.com/upload/software/2022/202201/20220125"
            tag: latest

          - version: 3.2.16
            repo: "https://static.tp-link.com/upload/software/2022/202201/20220125"
            tag: 3.2.16
            
          - version: 3.2.14
            repo: "https://static.tp-link.com/2020/202012/20201225"
            tag: 3.2.14

          - version: 3.2.10
            repo: "https://static.tp-link.com/2020/202004/20200420"
            tag: 3.2.10
          
          - version: 3.2.9
            repo: "https://static.tp-link.com/2020/202004/20200409"
            tag: 3.2.9
            
          - version: 3.2.6
            repo: "https://static.tp-link.com/2020/202001/20200116"
            tag: 3.2.6
            
          - version: 3.2.4
            repo: "https://static.tp-link.com/2019/201911/20191108"
            tag: 3.2.4
          
          - version: 3.2.1
            repo: "https://static.tp-link.com/2019/201909/20190906"
            tag: 3.2.1

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Image Build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/omada:${{ matrix.tag }}
          build-args: |
            OMADA_REPO=${{matrix.repo}}
            OMADA_VERSION=${{matrix.version}}