name: Security Checks
on:
  release:
    types: [published]
  schedule:
    - cron: "0 0 * * 0"
      
jobs:
  
  trivy:
     name: Trivy - Scan for Vuls 
     runs-on: ubuntu-latest
     strategy:
      fail-fast: false
      matrix:
        tag: [latest, 3.2.14, 3.2.10, 3.2.9, 3.2.6, 3.2.4, 3.2.1]
     
     steps:
        - name: Login to DockerHub
          uses: docker/login-action@v1 
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Pull docker image
          run: docker pull ${{secrets.DOCKER_USERNAME }}/omada:${{ matrix.tag }}
          
        - name: Trivy Action
          uses: homoluctus/gitrivy@v2  
          with:
            image: ${{secrets.DOCKER_USERNAME }}/omada:${{ matrix.tag }}
            token: ${{ secrets.GITHUB_TOKEN }}
            issue: false
  
  snyk:
    name: Snyk - Security Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:        
        tag: [latest, 3.2.14, 3.2.10, 3.2.9, 3.2.6, 3.2.4, 3.2.1]
    
    steps:
        - uses: actions/checkout@master
        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/docker@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
            image: ${{secrets.DOCKER_USERNAME }}/omada:${{matrix.tag}}
            args: --severity-threshold=high