name: Security Checks
on:
  push:
    paths-ignore: 
      - "README.md"
    branches:
    - master
  schedule:
    - cron:  "0 0 * * 0"
  pull_request:
    paths-ignore: 
      - "README.md"
    branches:
    - master
      

jobs:
  
  trivy:
     name: Trivy - Scan for Vuls 
     runs-on: ubuntu-latest
     strategy:
      fail-fast: false
      matrix:
        tags: [latest, 3.2.10-lts-20, 3.2.10-lts-18, 3.2.9-lts-20, 3.2.9-lts-18, 3.2.6-lts-20, 3.2.6-lts-18, 3.2.4-lts-20, 3.2.4-lts-18, 3.2.1-lts-20, 3.2.1-lts-18]
     steps:
        - name: Login to DockerHub Registry
          run: echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
        - name: Pull docker image
          run: docker pull ${{secrets.DOCKER_USER }}/omada:${{ matrix.tags }}
        - name: Trivy Action
          uses: homoluctus/gitrivy@v2  
          with:
            image: ${{secrets.DOCKER_USER }}/omada:${{ matrix.tags }}
            token: ${{ secrets.GITHUB_TOKEN }}
            issue: false
  
  snyk:
    name: Snyk - Security Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:        
        tag: [latest, 3.2.10-lts-20, 3.2.10-lts-18, 3.2.9-lts-20, 3.2.9-lts-18, 3.2.6-lts-20, 3.2.6-lts-18, 3.2.4-lts-20, 3.2.4-lts-18, 3.2.1-lts-20, 3.2.1-lts-18]
    steps:
        - uses: actions/checkout@master
        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/docker@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
            image: ${{secrets.DOCKER_USER }}/omada:${{matrix.tag}}
            args: --severity-threshold=high
