---
name: Security Checks
on:
  push:
    paths-ignore: 
      - "README.md"
      - ".github/**"
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"      

jobs:
  call-super-linter:
    uses: thost96/workflows/.github/workflows/security.yml@main